all:
	coqc Indexed.v
	coqc Induction.v
	coqc Sized.v
	coqc EqDec.v
	coqc NEList.v
	coqc Category.v
	coqc Success.v
	coqc Combinators.v
	coqc StringAsList.v
	coqc Char.v
	coqc Numbers.v
	coqc Running.v
	coqc Parseque.v
	coqc Examples.v

clean:
	rm -f *.vo *.glob
